# Default prometheus yml: https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
# Configuration docs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
  - job_name: "mysql"
    static_configs:
      - targets: [ "mysql-exporter:9104" ]
  - job_name: "rabbitmq"
    static_configs:
      - targets: [ "rabbitmq-exporter:9419" ]