services:
  memo:
    build: .
    image: memo
    container_name: memo-server
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./config:/app/config  # 本地的config目录映射到容器的app/config目录
    command: /app/memo
    restart: always

  db:
    image: mysql:8.0
    container_name: memo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: memo_lab3
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
