basePath: /api/v1
definitions:
  dto.Response:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 业务数据
      msg:
        description: 返回信息
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a memo api trial.
  title: Memo API
  version: "1.0"
paths:
  /memo/add:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 创建代办事项
      parameters:
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      - description: 正文
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 创建代办事项
      tags:
      - memo
  /memo/delete:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除代办事项。可删除指定id的事项，或者批量删除指定筛选条件的事项。
      parameters:
      - description: 代办事项id
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 删除代办事项
      tags:
      - memo
  /memo/list:
    get:
      description: 查询代办事项
      parameters:
      - description: 分页容量
        in: query
        name: limit
        type: integer
      - description: 起始页码
        in: query
        name: ps
        type: integer
      - description: 终止页码
        in: query
        name: pe
        type: integer
      - description: 筛选条件
        enum:
        - 0
        - 1
        - 2
        in: query
        name: filter
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 查询代办事项
      tags:
      - memo
  /memo/search:
    get:
      description: 搜索代办事项
      parameters:
      - description: 分页容量
        in: query
        name: limit
        type: integer
      - description: 起始页码
        in: query
        name: ps
        type: integer
      - description: 终止页码
        in: query
        name: pe
        type: integer
      - description: 必需，搜索关键词
        in: query
        name: keywords
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 搜索代办事项
      tags:
      - memo
  /memo/update:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 更新代办事项
      parameters:
      - description: 代办事项id
        in: formData
        name: id
        required: true
        type: integer
      - description: 标题
        in: formData
        name: title
        type: string
      - description: 正文
        in: formData
        name: content
        type: string
      - description: 状态
        enum:
        - 0
        - 1
        - 2
        in: formData
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 更新代办事项
      tags:
      - memo
  /user/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 用户登录
      tags:
      - user
  /user/signup:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: 用户注册
      tags:
      - user
swagger: "2.0"
