mysql:
  username: streamcore
  password: streamcore
  host: 127.0.0.1
  port: 3306
  dbname: streamcore
  charset: utf8mb4

server:
  host: 8080

general:
  page_size: 6
  image_size_limit: 5
  video_size_limit: 1024

redis:
  addr: 127.0.0.1:6379
  password: streamcore

rabbitmq:
  username: streamcore
  password: streamcore

etcd:
  addr: 127.0.0.1:2379

otel:
  collector_addr: 127.0.0.1:4317

services:
  api:
    name: api
    addr:
      - 0.0.0.0:10001
  user:
    name: user
    addr:
      - 0.0.0.0:20002
  video:
    name: video
    addr:
      - 0.0.0.0:20003
  interaction:
    name: interaction
    addr:
      - 0.0.0.0:20004
  social:
    name: social
    addr:
      - 0.0.0.0:20005
  chat:
    name: chat
    addr:
      - 0.0.0.0:20006
  group:
    name: group
    addr:
      - 0.0.0.0:20007
