mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbname: stream_core_lab4

server:
  host: 8080

general:
  page_size: 6

etcd:
  addr: 127.0.0.1:2379

services:
  api:
    name: api
    addr:
      - 0.0.0.0:20001
  user:
    name: user
    addr:
      - 0.0.0.0:20002
  video:
    name: video
    addr:
      - 0.0.0.0:20003
  interaction:
    name: interaction
    addr:
      - 0.0.0.0:20004
  social:
    name: social
    addr:
      - 0.0.0.0:20005